### ISSUE TITLE
Suggestion for Optimizing RClick's Right-Click "New" Feature on Desktop / 关于RClick桌面右键新建功能的优化建议

### ISSUE THREAD

**Issue by workingcoder** [wflixu/RClick#48]
Dear RClick Development Team,

First of all, thank you for developing such a practical application like RClick, which has greatly enhanced my file management experience on Mac.

During my usage, I noticed a minor issue: the right-click "New" feature works perfectly in Finder, but it doesn’t appear or function properly when I right-click directly on the desktop. Since many users are accustomed to managing files directly on the desktop, I was wondering if it would be possible to optimize this feature in future updates so that it works seamlessly in the desktop environment as well.

Thank you very much for your attention to user experience. I look forward to your reply and potential improvements.

/

尊敬的RClick开发团队，您好：

首先，感谢您开发了RClick这款实用的软件，极大地方便了我在Mac上的文件管理体验。

在使用过程中，我发现一个小问题：RClick 的右键新建功能在 Finder 中可以正常使用，但当我直接在桌面上右键点击时，该功能无法正常显示或使用。考虑到很多用户习惯于直接在桌面上进行文件管理，是否可以在未来的更新中优化这一功能，使其在桌面环境下也能正常使用？

非常感谢您对用户体验的关注，期待您的回复和改进建议。

**Comment by wflixu** [comment]
之前存在的问题，如果是 icloud 同步的文件夹，Finder sync extension 不生效，你看桌面是不是设置了icloud 同步。
icloud 同步文件夹中 菜单的问题还在想解决办法，欢迎PR

**Comment by riiciiii** [comment]
> 之前存在的问题，如果是 icloud 同步的文件夹，Finder sync extension 不生效，你看桌面是不是设置了icloud 同步。 icloud 同步文件夹中 菜单的问题还在想解决办法，欢迎PR

你好，我的电脑没有开启 icloud 同步的文件夹，桌面右键的新建功能也有问题。第一次授权全部磁盘权限后在桌面点了一次，当时看到可以创建。然后我去试了一下文件夹右键。再之后再点桌面右键，就没有反应了，没有新建文件了，连复制地址之类的也都没有了。

**Comment by Johnnyk1** [comment]
I cannot get it to work. OS 15.3.2. I made sure the extension is turned on.  I am not a mac newbie so I hesitated asking but ...

**Comment by wflixu** [comment]
> I cannot get it to work. OS 15.3.2. I made sure the extension is turned on. I am not a mac newbie so I hesitated asking but ...

please download new version

**Comment by Johnnyk1** [comment]
I downloaded 1.6.1, and I got the same dialog box, I click the settings, and the RC click is turned on. Still nothing. I am still being told Rcllick extension needs to be enabled.  I am using Better Mouse in case that may be a conflict. 
Thank you for the reply.

**Comment by wflixu** [comment]
> I downloaded 1.6.1, and I got the same dialog box, I click the settings, and the RC click is turned on. Still nothing. I am still being told Rcllick extension needs to be enabled.  I am using Better Mouse in case that may be a conflict. 
> Thank you for the reply.

I've released a new version v1.6.2. Could you help test if it's usable?

**Comment by Johnnyk1** [comment]
Sorry to say it is still not working. I used App Cleaner and EasyFind to delete all related files.  Installed RC 1.6.2. Clicked to allow the extension and still nothing. Beneath Enavble extension is still in grey. I am also running Ice if that makes a difference.

**Comment by Explorer-cc** [comment]
在macOS15.3.2中，只要添加了`usr/<usrname>/Desktop`到目录中，则可以直接在桌面进行文件管理。

![Image](https://github.com/user-attachments/assets/3cb6f5e4-b9c7-4281-afa6-3654a1082b41)

![Image](https://github.com/user-attachments/assets/7c34879d-f964-4d30-9acf-df9813c2ecc1)

**Comment by wflixu** [comment]
icloud 不同的文件夹不生效，这个暂时没办法解决，要重新添加一种拓展 File provider 才能设置同步文件夹的菜单

**Comment by wflixu** [comment]
#55
